config/routes.rb
Rails.application.routes.draw do
  root 'welcomes#index', as: 'home'

  get 'rank' => 'rank#index'
  get 'scored_bets' => 'rank#scored_bets'
  get 'send_pdf' => 'rank#send_pdf'
  
  resources :users_admin
  resources :tournaments
  resources :teams

  get 'games/per_tournament' => 'games#per_tournament'
  get 'games/round' => 'games#round'
  resources :games

  get 'bets/missing_bets' => 'bets#missing_bets'
  get 'bets/users_bet' => 'bets#show_bet_from_users'
  post 'bets/create_bets' => 'bets#create_bets'
  resources :bets

  get 'contact', to: 'messages#new', as: 'new_message'
  post 'contact', to: 'messages#create', as: 'create_message'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth' }
end

app/models/tournament.rb
class Tournament < ApplicationRecord
  has_many :games, dependent: :destroy
  has_many :charge, dependent: :destroy
  validates :name, :description, presence: true
  validates :name, uniqueness: { case_sensitive: false }
  has_attached_file :image, styles: { medium: "320x240#", thumb: "110x80#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  def self.tournament_pick(tournament = nil)
    @tournament_pick = tournament.blank? ? 'All bets' : 'All bets - '+Tournament.where(id: tournament[:id]).first.name+' tournament.'
    @no_bets_tournament = tournament.blank? ? 'You don\'t have any bet yet!' : 'You don\'t have bets for '+Tournament.where(id: tournament[:id]).first.name+' tournament.'
  end

end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  before_action :set_tournament, only: [:show, :edit, :update, :destroy]

  def index
  end

  def show
  end

  def edit
  end

  def update
    if @tournament.update(tournament_params)
      redirect_to @tournament, notice: 'Tournament was successfully updated.'
    else
      render :edit
    end
  end

  def new
    @tournament = Tournament.new
  end

  def create
    @tournament = Tournament.new(tournament_params)
    if @tournament.save
      redirect_to @tournament, notice: 'Tournament was successfully created.'
    else
      render :new
    end
  end

  def destroy
    @tournament.destroy
    redirect_to tournaments_url, notice: 'Tournament was successfully destroyed.'
  end

  private
  def tournament_params
    params.require(:tournament).permit(:name, :description, :image)
  end

  def set_tournament
    @tournament = Tournament.find(params[:id])
  end

end

app/helpers/tournament_helper.rb
module TournamentHelper
end

app/views/tournaments/_form.html.erb
<%= form_for @tournament, local: true, html: { multipart: true } do |f| %>

  <% if tournament.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tournament.errors.count, "error") %> prohibited this tournament from being saved:</h2>
      <ul>
      <% tournament.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :name %>
    <%= f.text_field :name, id: :tournament_name, class: "form-control"  %>
  </div>
  <div class="field form-group">
    <%= f.label :description %>
    <%= f.text_area :description, id: :tournament_description, class: "form-control"  %>
  </div>
  <div class="field form-group">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-default" %>
    <%= link_to 'Back', tournaments_path, class: "btn btn-default" %>
  </div>

<% end %>

app/views/tournaments/edit.html.erb
<h1>Editing Tournament</h1>

<%= render 'form', tournament: @tournament %>

app/views/tournaments/index.html.erb
<div class="jumbotron">
<h2>All Tournaments</h1>
<p>Those are all tournaments availables in the system.
  <% if user_admin %>
    <%= link_to 'New Tournament', new_tournament_path, class: "btn btn-dark" %>
  <% end %>
</p>
</div>
<div class="table-responsive">
  <table class="table table-striped">
  <% @tournaments.each do |tournament| %>
  <tbody>
    <tr class="tournament-vertical-align">
      <td class="middle-align">
        <figure>
          <%= link_to (image_tag tournament.image.url(:thumb), class: 'image'), games_per_tournament_path(tournament_id: tournament.id) %>
          <p><figcaption><%= tournament.name %></figcaption></p>
        </figure>
      </td>
      <td class="tournament-description"><%= tournament.description %></td>
      <% if user_admin %>
        <td class="middle-align"> <%= link_to 'Delete', tournament_path(tournament), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn-sm btn-dark" %> </td>
      <% end %>
    </tr>
  </tbody>
  <% end %>
</div>
  </table>

app/views/tournaments/new.html.erb
<h1>New Tournament</h1>

<%= render 'form', tournament: @tournament %>

app/views/tournaments/show.html.erb
<p>
  <%= image_tag @tournament.image.url, class: 'tournament-image' %>
</p>
<p>
  <%= @tournament.name %> <br>
  <%= @tournament.description %>
</p>

<% if user_admin %>
  <%= link_to 'Edit', edit_tournament_path(@tournament) %>
  <%= link_to 'Delete', tournament_path, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>
<%= link_to 'Back', tournaments_path, class: "btn btn-default" %>