config/routes.rb
Rails.application.routes.draw do
  root 'welcomes#index', as: 'home'

  get 'rank' => 'rank#index'
  get 'scored_bets' => 'rank#scored_bets'
  get 'send_pdf' => 'rank#send_pdf'
  
  resources :users_admin
  resources :tournaments
  resources :teams

  get 'games/per_tournament' => 'games#per_tournament'
  get 'games/round' => 'games#round'
  resources :games

  get 'bets/missing_bets' => 'bets#missing_bets'
  get 'bets/users_bet' => 'bets#show_bet_from_users'
  post 'bets/create_bets' => 'bets#create_bets'
  resources :bets

  get 'contact', to: 'messages#new', as: 'new_message'
  post 'contact', to: 'messages#create', as: 'create_message'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth' }
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  def index
  end
end

app/views/welcomes/index.html.erb
<div id="home_image">
  <%= image_tag("player_pele.png") %>
</div>
<div class="panel panel-default">
  <div class="panel-body">
    <div class="row">
      <div class="col-md-5">
        <h4>Are you an admin?</h4>
        <ul>
          <li>You can create
            <%= link_to 'Teams', new_team_path %>
          </li>
          <li>You can create
            <%= link_to 'Tournaments', new_tournament_path %>
          </li>
          <li>You can create games but you need create teams and tournaments first</li>
          <li>You can do your
            <%= link_to 'Bets', bets_path %>
          </li>
          <li>You can send the rank by email for all users <br/>
            <mark> Go to a rank of a tournament and click in Send PDF</mark>
          </li>
          <li>
            You can see all <%= link_to "Users", users_admin_index_path %> of the system
          </li>
        </ul>
      </div>
      <div class="col-md-5">
        <h4>Are you a user?</h4>
        <ul>
          <li>You can create your <%= link_to 'Bets', bets_path %> until one hour before the game</li>
          <li>You can create all best at once or do one at a time</li>
          <li>You can see all bets of a game, if the betting time is over. <br/>
            Choose games from a tournament and click in Bets to see all bets.
          </li>
          <li>You can see all bets of an user, in the rank <br/>
            Go to a rank from a tournament and click in the user name.
          </li>
          <li>You can <%= link_to "Contact", new_message_path %> the admin</li>
        </ul>
      </div>
    </div>
  </div>
</div>