config/routes.rb
Rails.application.routes.draw do
  root 'welcomes#index', as: 'home'

  get 'rank' => 'rank#index'
  get 'scored_bets' => 'rank#scored_bets'
  get 'send_pdf' => 'rank#send_pdf'
  
  resources :users_admin
  resources :tournaments
  resources :teams

  get 'games/per_tournament' => 'games#per_tournament'
  get 'games/round' => 'games#round'
  resources :games

  get 'bets/missing_bets' => 'bets#missing_bets'
  get 'bets/users_bet' => 'bets#show_bet_from_users'
  post 'bets/create_bets' => 'bets#create_bets'
  resources :bets

  get 'contact', to: 'messages#new', as: 'new_message'
  post 'contact', to: 'messages#create', as: 'create_message'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth' }
end

app/controllers/users_admin_controller.rb
class UsersAdminController < ApplicationController
  before_action :set_user_config, only: [:show, :edit, :update]
  before_action {check_admin home_path}
  def index
    @users = User.all
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to users_admin_index_url, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  private
  def set_user_config
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :admin)
  end
end

app/views/users_admin/_form.html.erb
<%= form_for @user, local: true, url: users_admin_path ,html: { multipart: true } do |f| %>

  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :name %>
    <%= f.text_field :name, id: :user_name, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :email %>
    <%= f.text_field :email, id: :user_email, class: "form-control"  %>
  </div>
  <div class="field">
    <%= f.label :admin %>
    <%= f.check_box :admin, id: :user_admin %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-default" %>
    <%= link_to 'Back', users_admin_index_path, class: "btn btn-default" %>
  </div>
<% end %>

app/views/users_admin/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

app/views/users_admin/index.html.erb
<h2>Users</h2>
<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <th>Name</th>
      <th>Email</th>
      <th>Number of bets</th>
      <th>Created</th>
    </thead>
    <tbody>
      <% @users.each do|user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.bets.count %></td>
        <td><%= user.created_at %></td>
        <td><%= link_to 'Profile', edit_users_admin_path(user), class: "btn btn-default" %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>