config/routes.rb
Rails.application.routes.draw do
  root 'welcomes#index', as: 'home'

  get 'rank' => 'rank#index'
  get 'scored_bets' => 'rank#scored_bets'
  get 'send_pdf' => 'rank#send_pdf'
  
  resources :users_admin
  resources :tournaments
  resources :teams

  get 'games/per_tournament' => 'games#per_tournament'
  get 'games/round' => 'games#round'
  resources :games

  get 'bets/missing_bets' => 'bets#missing_bets'
  get 'bets/users_bet' => 'bets#show_bet_from_users'
  post 'bets/create_bets' => 'bets#create_bets'
  resources :bets

  get 'contact', to: 'messages#new', as: 'new_message'
  post 'contact', to: 'messages#create', as: 'create_message'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth' }
end

app/views/layouts/_games.html.erb
<% if !@games.blank? %>
<div>
  <div class="table-responsive">
    <table class="table table-striped">
      <thead>
        <tr>
          <th><strong>Tournament:</strong></th>
          <th colspan="3"><%= @games.first.tournament.name %></th>
          <th>Date</th>
        </tr>
      </thead>
      <tbody>
        <% @games.each_with_index do |game, index| %>
          <tr>
            <th scope="row"><br/>Game #<%= index + 1 %><br/>Round: <%= game.round %></th>
            <td class="middle-align"><%= image_tag game.first_team.image, class: "#{game.first_team.team_type}_team_image img-rounded", title: game.first_team.name %></td>
            <td class="middle-align">
              <% if !game.score_first_team.blank? &&  !game.score_second_team.blank?%>
                  <%= game.score_first_team %>
                  <strong>X</strong>
                  <%= game.score_second_team %>
                <% else %>
                  <strong> Waiting game </strong>
                <% end %>
            </td>
            <td class="middle-align"><%= image_tag game.second_team.image, class: "#{game.second_team.team_type}_team_image img-rounded", title: game.second_team.name  %></td>
            <td class="middle-align"><%= game.date.strftime("%d/%m/%Y at %I:%M %p") %></td>
            <td class="middle-align"><%= link_to "Bets" ,bets_users_bet_path(game_id: game.id, tournament_id: game.tournament.id) %> </td>
            <% if user_admin %>
              <td class="middle-align">
                <%= link_to 'Edit', edit_game_path(game), class: "btn-sm btn-dark" %>
                <%= link_to 'Delete', game_path(game), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn-sm btn-dark" %>
              </td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to 'Bets', home_path, class: 'navbar-brand' %>
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#collapse-menu">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse" id="collapse-menu">
      <ul class="nav navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to 'Teams', teams_path %>
        </li>
        <li class="nav-item">
          <%= link_to 'Tournaments', tournaments_path %>
        </li>
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Games <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <% @tournaments.each do |tournament| %>
                <li><%= link_to tournament.name, games_per_tournament_path(tournament_id: tournament.id)  %></li>
              <% end %>
            </ul>
          </li>
          <li class="nav-item">
            <%= link_to 'My bets', bets_path %>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Rank <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <% @tournaments.each do |tournament| %>
                <li><%= link_to tournament.name, rank_path(tournament_id: tournament.id)  %></li>
              <% end %>
            </ul>
          </li>
        <% end %>
        <li><%= link_to "Contact", new_message_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_admin %>
          <li><%= link_to "Users", users_admin_index_path %></li>
        <% end %>
        <% if user_signed_in? %>
          <li><%= link_to current_user.name, edit_user_registration_path %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
          <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WorldCupBet</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <% flash.each do |name, msg| %>
      <% flashClass = 'alert alert-info' %>
      <% if flash[:alert] %>
        <% flashClass = 'alert alert-danger' %>
      <% end %>
        <%= content_tag(:div, msg, class: flashClass) %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/pdf.html.erb
<!DOCTYPE html>
<html>
<head>
<title>PDF</title>
  <%= wicked_pdf_stylesheet_link_tag "pdf" -%>
  <%= wicked_pdf_stylesheet_link_tag "application" , media: 'all', 'data-turbolinks-track': 'reload' -%>
  <%= wicked_pdf_javascript_include_tag "number_pages" %>
  <%= wicked_pdf_javascript_include_tag "application", 'data-turbolinks-track': 'reload'  %>
</head>
<body>
  <div class='content container'>
    <%= yield %>
  </div>
</body>
</html>